const PARTICLE_COUNT = 5000;
const PARTICLE_SPREAD = 10;
const PARTICLE_SIZE = 0.015;
const PARTICLE_COLOR = "#6366f1";
const ROTATION_SPEED = 0.05;
const ROTATION_AMPLITUDE = 0.2;
const MOUSE_INFLUENCE = 0.1;
const CAMERA_POSITION: [number, number, number] = [0, 0, 5];
const CAMERA_FOV = 60;

export {
    CAMERA_FOV,
    CAMERA_POSITION,
    MOUSE_INFLUENCE,
    PARTICLE_COLOR,
    PARTICLE_COUNT,
    PARTICLE_SIZE,
    PARTICLE_SPREAD,
    ROTATION_AMPLITUDE,
    ROTATION_SPEED
};

